const titles = [
    "Aspiring Pirate",
    "Treasure Hunter",
    "Part-time Spy",
    "Powernap Activist",
    "Ideas Samurai",
    "Junior Revolutionist",
    "Cookies Enthusiast",
    "Potatoe Farmer",
    "Waterbending Master",
    "Proficient Sorcerer",
    "Freelance Wizard",
    "Orc Rights Advocate",
    "Exiled Prince",
    "Bandito",
    "Occasional Werewolf",
    "Double Agent",
    "Citizen of Pandora",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
  ];

  export default titles

