const titles = [
    "Aspiring Pirate",
    "Treasure Hunter",
    "Part-time Spy",
    "Powernap Activist",
    "Ideas Samurai",
    "Junior Revolutionist",
    "Bank Robber",
    "Confidence Man",
    "Cookies Enthusiast",
    "Prison Escapee",
    "Unethical Pillow Fighter",
    "Potatoe Farmer",
    "Waterbending Master",
    "Proficient Sorcerer",
    "Freelance Wizard",
    "Orc Rights Defender",
    "Lieutenant of Something",
    "Special Operations",
    "Exiled Prince",
    "Occasional Werewolf",
    "Double Agent",
    "Ex-leader of the Omaticaya Clan",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
    "null",
  ];

  export default titles

